nome = input("Digite o seu nome completo:")
cpf = input("Digite seu CPF:")
idade = input("Digite sua idade:")

print('-------------------------')
print('Confirmação de cadastro: ')
print('Nome:{}'.format(nome))
print('CPF:{}'.format(cpf))
print('Idade:{}'.format(idade))
print('\n')
print('-------------------------')
